// Central place for all category/static links used by LeftRail & MobileMenu

export const CATEGORIES = [
  { slug: "confessions", label: "Confessions" },
  { slug: "posts", label: "Posts" },
  { slug: "product-reviews", label: "Product Reviews" },
  { slug: "movie-reviews", label: "Movie Reviews" },
  { slug: "place-reviews", label: "Place Reviews" },
  { slug: "post-ideas", label: "Post Ideas" },
  { slug: "post-ads", label: "Post Ads" },
  { slug: "business-info", label: "Business Info" },
  { slug: "sports", label: "Sports" },
  { slug: "science", label: "Science" },
  { slug: "automobile", label: "Automobile" },
  { slug: "education", label: "Education" },
  { slug: "anime", label: "Anime" },
  { slug: "technology", label: "Technology" },
  { slug: "travel", label: "Travel" },
  { slug: "food", label: "Food" },
  { slug: "health", label: "Health" },
  { slug: "finance", label: "Finance" },
  { slug: "fashion", label: "Fashion" },
  { slug: "books", label: "Books" },
  { slug: "music", label: "Music" },
  { slug: "gaming", label: "Gaming" },
  { slug: "photography", label: "Photography" },
  { slug: "art", label: "Art" },
  { slug: "history", label: "History" },
  { slug: "relationships", label: "Relationships" },
  { slug: "career", label: "Career" },
  { slug: "pets", label: "Pets" },
  { slug: "gardening", label: "Gardening" },
  { slug: "diy", label: "DIY" },
  { slug: "parenting", label: "Parenting" },
  { slug: "fitness", label: "Fitness" },
];

export const STATIC_PAGES = [
  { href: "community", label: "Community" },
  { href: "faq", label: "FAQ" },
  { href: "rules", label: "Rules" },
  { href: "policy", label: "Policy" },
  { href: "privacy", label: "Privacy" },
  { href: "terms", label: "Terms" },
  { href: "trademark", label: "Trademark" },
];
