export const CATEGORIES = [
  { slug: "confessions", name: "Confessions" },
  { slug: "posts", name: "Posts" },
  { slug: "product-reviews", name: "Product Reviews" },
  { slug: "movie-reviews", name: "Movie Reviews" },
  { slug: "place-reviews", name: "Place Reviews" },
  { slug: "post-ideas", name: "Post Ideas" },
  { slug: "post-ads", name: "Post Ads" },
  { slug: "business-info", name: "Business Info" },
  { slug: "sports", name: "Sports" },
  { slug: "science", name: "Science" },
  { slug: "automobile", name: "Automobile" },
  { slug: "education", name: "Education" },
  { slug: "anime", name: "Anime" },
  { slug: "technology", name: "Technology" },
  { slug: "travel", name: "Travel" },
  { slug: "food", name: "Food" },
  { slug: "health", name: "Health" },
  { slug: "finance", name: "Finance" },
  { slug: "fashion", name: "Fashion" },
  { slug: "books", name: "Books" },
  { slug: "music", name: "Music" },
  { slug: "gaming", name: "Gaming" },
  { slug: "photography", name: "Photography" },
  { slug: "art", name: "Art" },
  { slug: "history", name: "History" },
  { slug: "relationships", name: "Relationships" },
  { slug: "career", name: "Career" },
  { slug: "pets", name: "Pets" },
  { slug: "gardening", name: "Gardening" },
  { slug: "diy", name: "DIY" },
  { slug: "parenting", name: "Parenting" },
  { slug: "fitness", name: "Fitness" },
];

export function findCategory(slug) {
  return CATEGORIES.find((c) => c.slug === slug) || null;
}
