// lib/categories.js
const categories = [
  { name: "Confessions", slug: "confessions" },
  { name: "Posts", slug: "posts" },
  { name: "Product Reviews", slug: "product-reviews" },
  { name: "Movie Reviews", slug: "movie-reviews" },
  { name: "Place Reviews", slug: "place-reviews" },
  { name: "Post Ideas", slug: "post-ideas" },
  { name: "Post Ads", slug: "post-ads" },
  { name: "Business Info", slug: "business-info" },
  { name: "Sports", slug: "sports" },
  { name: "Science", slug: "science" },
  { name: "Automobile", slug: "automobile" },
  { name: "Education", slug: "education" },
  { name: "Anime", slug: "anime" },
  { name: "Technology", slug: "technology" },
  { name: "Travel", slug: "travel" },
  { name: "Food", slug: "food" },
  { name: "Health", slug: "health" },
  { name: "Finance", slug: "finance" },
  { name: "Fashion", slug: "fashion" },
  { name: "Books", slug: "books" },
  { name: "Music", slug: "music" },
  { name: "Gaming", slug: "gaming" },
  { name: "Photography", slug: "photography" },
  { name: "Art", slug: "art" },
  { name: "History", slug: "history" },
  { name: "Relationships", slug: "relationships" },
  { name: "Career", slug: "career" },
  { name: "Pets", slug: "pets" },
  { name: "Gardening", slug: "gardening" },
  { name: "DIY", slug: "diy" },
  { name: "Parenting", slug: "parenting" },
  { name: "Fitness", slug: "fitness" },
];

export default categories;
